version: "3.8"

services:
  # Uncomment this section if you want to run your app in the same Docker Compose setup
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"  # RedisInsight UI will be accessible at http://localhost:8001
    depends_on:
      - redis  # Ensures RedisInsight starts after Redis

volumes:
  redis_data:
